backend:
  name: github
  repo: pbarbon93-wq/bncarpentry-site
  branch: main
  base_url: https://pbarbon93-wq.github.io/bncarpentry-site
  open_authoring: false

media_folder: "images/uploads"
public_folder: "/images/uploads"
publish_mode: editorial_workflow

collections:
  - name: "site"
    label: "Site Settings"
    files:
      - file: "content/site.json"
        label: "General"
        name: "general"
        fields:
          - { label: "Brand Name", name: "brand_name", widget: "string" }
          - { label: "Hero Title", name: "hero_title", widget: "string" }
          - { label: "Hero Subtitle", name: "hero_subtitle", widget: "string" }
          - { label: "About Text", name: "about_text", widget: "text" }
          - label: "Contact"
            name: "contact"
            widget: "object"
            fields:
              - { label: "Phone (display)", name: "phone_display", widget: "string" }
              - { label: "WhatsApp Number (digits only)", name: "phone_whatsapp", widget: "string" }
              - { label: "Email", name: "email", widget: "string" }
              - { label: "Location", name: "location", widget: "string" }
          - label: "Social Links"
            name: "socials"
            widget: "object"
            fields:
              - { label: "Facebook", name: "facebook", widget: "string", required: false }
              - { label: "Instagram", name: "instagram", widget: "string", required: false }
              - { label: "WhatsApp URL", name: "whatsapp", widget: "string", required: false }

  - name: "services"
    label: "Services"
    files:
      - file: "content/services.json"
        label: "Services List"
        name: "services"
        fields:
          - label: "Services"
            name: "items"
            widget: "list"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Icon (emoji or text)", name: "icon", widget: "string", required: false }
              - { label: "Description", name: "description", widget: "text" }

  - name: "gallery"
    label: "Gallery"
    files:
      - file: "content/gallery.json"
        label: "Gallery Images"
        name: "gallery"
        fields:
          - label: "Images"
            name: "images"
            widget: "list"
            field: { label: "Image", name: "image", widget: "image" }
