[build]
  publish = "."
  command = ""

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/admin"
  to = "/admin/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[[headers]]
  for = "/admin/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Content-Type = "text/html; charset=UTF-8"
